### ISSUE TITLE
Error connecting stripe

### ISSUE THREAD

**Issue by Daniellop1** [jackrobertscott/authpack#24]
I could not connect with stripe because it indicates an error

**Comment by obilaz** [comment]
Same here, here is the error

 "Standard OAuth is disabled for this Stripe Connect integration. If you own this integration, you can enable the Standard OAuth flow in the Connect Settings page in your dashboard."
 
 The way to activate it is pretty straightforwad: Settings > Connect Settings > The switch to enable Standard OAuth is at the bottom of the page

**Comment by reeceatkinson** [comment]
Same

**Comment by reeceatkinson** [comment]
@jackrobertscott is there anyway it can be re-enabled?
